import type { Config } from "tailwindcss";

/**
 * EARTHLINK Philippines design tokens.
 *
 * The full reasoning lives in DESIGN_DIRECTION.md. The short version:
 *
 * The palette is derived from the client's own concept document, which already
 * contained a colour system nobody had noticed. The concept defines six case
 * states (Reported, Under verification, Referred, Action in progress, Resolved,
 * Monitoring) and seven map categories, each with a colour. Those are treated
 * here as a first-class part of the brand rather than as UI chrome.
 *
 * Two consequences follow, and both are deliberate:
 *
 * 1. The brand accent cannot be red, orange, amber, blue, green or grey, because
 *    all six are spoken for by the case states. Using one would make the interface
 *    ambiguous. Hence `signal`, a hi-vis chartreuse that sits outside the whole
 *    status ramp and reads as field equipment rather than decoration.
 *
 * 2. Every status and category carries TWO tones. `pin` is the saturated tone for
 *    dots, map pins and fills, which are graphic and need 3:1. `text` is the
 *    darkened tone for labels on the light ground, which carry meaning as text and
 *    need 4.5:1. A single tone failed twelve of the pairs. See docs/CONTRAST.md,
 *    which is generated by npm run contrast and gated in npm run verify.
 *
 * The ground is a COOL green-grey paper, not the warm cream used by most of the
 * studio's recent work. That break is the point: this is water, air and
 * measurement, not hospitality.
 */

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx,mdx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
    "./content/**/*.{md,mdx}",
  ],
  theme: {
    container: {
      center: true,
      // Gutters live here so no component ever restates them.
      padding: { DEFAULT: "1.25rem", sm: "1.5rem", lg: "2rem" },
      // 1240 rather than 1280, to keep line length readable.
      screens: { "2xl": "1240px" },
    },
    extend: {
      colors: {
        brand: {
          ink: "#07231E", // mangrove ink. Body type and every dark band.
          deep: "#0B3B32", // mid mangrove. Headings on the light ground.
          primary: {
            DEFAULT: "#0E6B55",
            600: "#0C5A47",
            700: "#0A4A3B",
          },
          // Hi-vis chartreuse. NEVER small text on the light ground: 1.18:1.
          // On dark surfaces, as large type, or as a graphic element only.
          signal: {
            DEFAULT: "#C2F24D",
            400: "#D3F67E",
            600: "#A8D92F",
          },
          paper: "#F1F5F1", // cool page ground
          surface: "#FFFFFF", // raised cards
          line: "#D4DED8", // hairlines and borders
        },

        // The six case states from the client's concept.
        status: {
          reported: { DEFAULT: "#DF3023", text: "#C3281D" },
          verifying: { DEFAULT: "#F79009", text: "#965705" },
          referred: { DEFAULT: "#CA8A04", text: "#895E03" },
          progress: { DEFAULT: "#2E90FA", text: "#0563C9" },
          resolved: { DEFAULT: "#12B76A", text: "#0C7544" },
          monitoring: { DEFAULT: "#98A2B3", text: "#5A667A" },
        },

        // The seven EARTH Map category layers from the concept.
        // Waste is violet, not the recycling green its icon implies, because a
        // second green on a map that already uses green for Forest and green for
        // Resolved would be unreadable.
        cat: {
          water: { DEFAULT: "#0EA5E9", text: "#096D9A" },
          forest: { DEFAULT: "#168740", text: "#137538" },
          waste: { DEFAULT: "#8C52EF", text: "#7B39ED" },
          air: { DEFAULT: "#67778F", text: "#59677C" },
          biodiversity: { DEFAULT: "#0D9488", text: "#0A7269" },
          land: { DEFAULT: "#A86607", text: "#925906" },
          hazard: { DEFAULT: "#DE3030", text: "#C72020" },
        },
      },

      fontFamily: {
        // Always via next/font CSS variables, always with a real fallback stack.
        display: ["var(--font-display)", "Helvetica Neue", "Arial", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        // Data only. Case numbers, coordinates, timestamps, counters. Never prose.
        data: ["var(--font-data)", "ui-monospace", "SFMono-Regular", "Consolas", "monospace"],
      },

      fontSize: {
        // Clamp tokens in the config, not breakpoint ladders in the markup.
        // Line height shrinks as size grows.
        "display-2xl": ["clamp(3rem, 8vw, 6rem)", { lineHeight: "0.95", letterSpacing: "-0.03em" }],
        "display-xl": ["clamp(2.5rem, 5.5vw, 4.25rem)", { lineHeight: "1.02", letterSpacing: "-0.025em" }],
        "display-lg": ["clamp(2rem, 4vw, 3rem)", { lineHeight: "1.08", letterSpacing: "-0.02em" }],
        "display-md": ["clamp(1.5rem, 2.5vw, 2rem)", { lineHeight: "1.15", letterSpacing: "-0.015em" }],
      },

      letterSpacing: {
        // One eyebrow tracking value for the whole project. The playbook notes this
        // drifts from 0.18em to 0.35em across the portfolio and says pick one.
        eyebrow: "0.22em",
      },

      maxWidth: {
        prose: "68ch",
      },

      boxShadow: {
        // Tinted with mangrove ink, never black. rgb(7, 35, 30) is `ink`.
        soft: "0 2px 8px -2px rgba(7, 35, 30, 0.08), 0 8px 24px -8px rgba(7, 35, 30, 0.10)",
        lift: "0 8px 30px -6px rgba(7, 35, 30, 0.18)",
        inset: "inset 0 1px 0 0 rgba(255, 255, 255, 0.06)",
      },

      transitionTimingFunction: {
        // Expo-out. Never `ease`, never `linear`.
        expo: "cubic-bezier(0.16, 1, 0.3, 1)",
      },

      keyframes: {
        "fade-up": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pin-drop": {
          "0%": { opacity: "0", transform: "translateY(-10px) scale(0.7)" },
          "70%": { opacity: "1", transform: "translateY(1px) scale(1.04)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        "rail-fill": {
          from: { transform: "scaleX(0)" },
          to: { transform: "scaleX(1)" },
        },
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
        ping: {
          "0%": { transform: "scale(1)", opacity: "0.55" },
          "80%, 100%": { transform: "scale(2.4)", opacity: "0" },
        },
      },

      animation: {
        "fade-up": "fade-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) both",
        "pin-drop": "pin-drop 0.5s cubic-bezier(0.16, 1, 0.3, 1) both",
        "rail-fill": "rail-fill 0.7s cubic-bezier(0.16, 1, 0.3, 1) both",
        marquee: "marquee 38s linear infinite",
        ping: "ping 2.4s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
