import mapData from "@/data/ph-map.json";

/**
 * The EARTH Map projection.
 *
 * The geometry in data/ph-map.json is generated by scripts/build-map.mjs from
 * PSA PSGC administrative boundaries. This module holds the one function that has
 * to agree with that script exactly: the projection that turns a latitude and
 * longitude into a position in the SVG viewBox.
 *
 * If these two ever disagree, every pin lands in the wrong place, so
 * scripts/verify-cases.mjs re-derives the projection from the data file's own
 * stored bounds and checks all 37 sample cases land in the region they claim. That
 * check runs in npm run qa.
 */

export const MAP = mapData;

const { lonMin, lonMax, latMin, latMax } = MAP.bounds;
const VW = MAP.viewBox.width;
const VH = MAP.viewBox.height;

const MID_LAT_RAD = (((latMin + latMax) / 2) * Math.PI) / 180;
const LON_SPAN = (lonMax - lonMin) * Math.cos(MID_LAT_RAD);
const LAT_SPAN = latMax - latMin;

const SCALE = Math.min(VW / LON_SPAN, VH / LAT_SPAN);
const OFF_X = (VW - LON_SPAN * SCALE) / 2;
const OFF_Y = (VH - LAT_SPAN * SCALE) / 2;

export interface MapPoint {
  x: number;
  y: number;
}

/** Latitude and longitude to a position inside the map viewBox. */
export function project(lat: number, lng: number): MapPoint {
  return {
    x: (lng - lonMin) * Math.cos(MID_LAT_RAD) * SCALE + OFF_X,
    y: (latMax - lat) * SCALE + OFF_Y,
  };
}

export const VIEW_BOX = `0 0 ${VW} ${VH}`;
export const VIEW_WIDTH = VW;
export const VIEW_HEIGHT = VH;

/**
 * All island shapes, largest first.
 *
 * `detail` trades completeness for bytes. The full set is 457 shapes, which is
 * right on the map page where the map IS the page. The homepage hero only needs
 * the country to be recognisable behind a headline, so it takes the largest
 * shapes and skips 300 islands that would each render at under two pixels.
 */
export function getShapes(detail: "full" | "hero" = "full"): string[] {
  const all = MAP.regions.flatMap((r) => r.paths);
  // Path string length is a good proxy for island size here: bigger islands keep
  // more vertices after simplification.
  const sorted = [...all].sort((a, b) => b.length - a.length);
  return detail === "hero" ? sorted.slice(0, 90) : sorted;
}

/** Region outlines keyed by PSGC short code, for the region filter on the map page. */
export function getRegions() {
  return MAP.regions.map((r) => ({ code: r.code, short: r.short, name: r.name, paths: r.paths }));
}

export const MAP_SOURCE = {
  text: MAP.source,
  url: MAP.sourceUrl,
};
